name: Crawle the web site

# see: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  push:
    branches:
      - main
      - gh-actions

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libkrb5-dev wget tree
          wget -O jq -q https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
          chmod +x jq && mv jq /usr/local/bin
      - name: Crawl from the web site
        run: |
          ./sbt crawl
          ls -lhtr ./original && tree ./original
      - name: Commit crawled files
        run: |
          git config --global user.email yuokada@users.noreply.github.com
          git config --global user.name "Yukihiro Okada"
          git add ./original
          git commit -m "[skip ci] Update crawled files" ./original
      - name: Push crawled files
        run: |
          git push origin HEAD