name: Crawle the web site

# see: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  workflow_dispatch: # Allow running on-demand
  schedule:
    - cron:  '0 3 * * *'
    - cron:  '0 2 3 * *' # For monthly crawling


jobs:
  daily_crawl:
    if: contains(github.event.schedule, '0 3 * * *')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libkrb5-dev wget tree
          wget -O jq -q https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
          chmod +x jq && mv jq /usr/local/bin
      - name: Crawl from the web site
        run: |
          ./sbt crawl
          ls -lhtr ./original && tree ./original
      - name: Commit crawled files
        run: |
          git config --global user.email yuokada@users.noreply.github.com
          git config --global user.name "Yukihiro Okada"
          git add ./original
          git commit -m "[skip ci] Update crawled files" ./original || true
      - name: Push crawled files
        run: |
          git push origin HEAD

  # see: https://github.com/orgs/community/discussions/25662
  monthly_crawl:
    if: contains(github.event.schedule, '0 2 3 * *') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libkrb5-dev wget tree
          wget -O jq -q https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
          chmod +x jq && mv jq /usr/local/bin
      - name: Crawl from the web site
        run: |
          ./sbt "crawl last month"
      - name: Commit crawled files
        run: |
          git config --global user.email yuokada@users.noreply.github.com
          git config --global user.name "Yukihiro Okada"
          git add ./original
          git commit -m "[skip ci] Update crawled files on monthly crawling scheduler" ./original || true
      - name: Push crawled files
        run: |
          git push origin HEAD
