name: Crawle the web site

# see: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          "3.9",
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libkrb5-dev wget tree
          wget -O jq -q https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
          chmod +x jq && mv jq /usr/local/bin
      - name: Crawl from the web site
        run: |
          ./sbt crawl
          ls -lhtr && tree
          yq -h
          yq -c "." db.yaml > db.json
#      - name: Commit db.json
#        run: |
#          git config --global user.email yuokada@users.noreply.github.com
#          git config --global user.name "Yukihiro Okada"
#          git add db.json
#          git commit -m "[skip ci] Update db.json" db.json
#      - name: Push db.json
#        run: |
#          git push origin HEAD